In [10]:
import sys
sys.path.append("..")
import torch
import torch.nn as nn
import torch.nn.functional as F

from models import *
from transformers import GPT2Model, GPT2Config

In [2]:
N, L, d, nh = 7, 5, 6, 2

In [3]:
af_block = AFBlock(MyTfConfig(embed_dim=d, num_heads=nh))
af_block.attn = nn.MultiheadAttention(d, nh, batch_first=True)
af_block.attn.in_proj_weight.data[0:d,:] = torch.eye(d)
af_block.attn.in_proj_weight.data[d:2*d,:] = torch.eye(d)
af_block.attn.in_proj_weight.data[2*d:3*d,:] = torch.eye(d)
af_block.attn.out_proj.weight.data = torch.eye(d)

mha = nn.MultiheadAttention(d, nh, batch_first=True)
mha.in_proj_weight.data[0:d,:] = torch.eye(d)
mha.in_proj_weight.data[d:2*d,:] = torch.eye(d)
mha.in_proj_weight.data[2*d:3*d,:] = torch.eye(d)
mha.out_proj.weight.data = torch.eye(d)

In [4]:
# x = torch.ones(N,L,d)
# x = torch.cat([i * torch.ones(N,1,d) for i in range(1,L+1)], dim=1)
x = torch.cat([1 * torch.ones(N,1,d) for i in range(1,L+1)], dim=1)
bool_mask = torch.triu(torch.ones(L,L), diagonal=1).view(1,L,L).repeat(N*nh,1,1).bool()
float_mask = (1.0 - torch.tril(torch.ones(L,L), diagonal=0)).view(1,L,L).repeat(N*nh,1,1) * -9999

In [5]:
out, wt = mha(x,x,x, attn_mask=bool_mask)
(out.shape, wt.shape, out, wt)

(torch.Size([7, 5, 6]),
 torch.Size([7, 5, 5]),
 tensor([[[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1., 1.],
 

In [6]:
out, wt = mha(x,x,x, attn_mask=float_mask)
(out.shape, wt.shape, out, wt)

(torch.Size([7, 5, 6]),
 torch.Size([7, 5, 5]),
 tensor([[[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1., 1.],
 

In [7]:
af_mask = torch.randint(0,2,(N,L))
af_mask[:,0] = 1
af_mask[0,] = torch.ones(L)

out, wt = af_block(x, attention_mask=af_mask)
(out.shape, wt.shape, out, wt)

(torch.Size([7, 5, 6]),
 torch.Size([7, 5, 5]),
 tensor([[[ 0.3132, -0.4609, -0.5618, -0.0073,  1.9570, -1.2402],
          [ 0.3132, -0.4609, -0.5618, -0.0073,  1.9570, -1.2402],
          [ 0.3132, -0.4609, -0.5618, -0.0073,  1.9570, -1.2402],
          [ 0.3132, -0.4609, -0.5618, -0.0073,  1.9570, -1.2402],
          [ 0.3132, -0.4609, -0.5618, -0.0073,  1.9570, -1.2402]],
 
         [[ 0.3132, -0.4609, -0.5618, -0.0073,  1.9570, -1.2402],
          [ 0.3132, -0.4609, -0.5618, -0.0073,  1.9570, -1.2402],
          [ 0.3132, -0.4609, -0.5618, -0.0073,  1.9570, -1.2402],
          [ 0.3132, -0.4609, -0.5618, -0.0073,  1.9570, -1.2402],
          [ 0.3132, -0.4609, -0.5618, -0.0073,  1.9570, -1.2402]],
 
         [[ 0.3132, -0.4609, -0.5618, -0.0073,  1.9570, -1.2402],
          [ 0.3132, -0.4609, -0.5618, -0.0073,  1.9570, -1.2402],
          [ 0.3132, -0.4609, -0.5618, -0.0073,  1.9570, -1.2402],
          [ 0.3132, -0.4609, -0.5618, -0.0073,  1.9570, -1.2402],
          [ 0.3132, -0

In [8]:
af_mask

tensor([[1, 1, 1, 1, 1],
        [1, 0, 1, 0, 1],
        [1, 0, 1, 0, 0],
        [1, 1, 0, 0, 0],
        [1, 1, 0, 0, 1],
        [1, 1, 0, 1, 1],
        [1, 0, 0, 1, 1]])

In [15]:
gpt2 = GPT2Model(GPT2Config())

In [19]:
x = torch.rand(2,10,768)
attn_mask = torch.randint(0,2,(2,10))
out = gpt2(inputs_embeds=x, attention_mask=attn_mask)

In [ ]:
###